env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  strict: 0
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  react/jsx-uses-vars:
    - error
  react/jsx-uses-react:
    - error
  no-console:
    - 0
  no-unused-vars: [2, {"argsIgnorePattern": "^_"}]
globals:
  process: true
  window: true
  document: true
  console: true
  __dirname: true
  require: true
  module: true
